baseurl = "https://www.roastorband.no/"
languageCode = "en-us"
title = "Røa Storband"

# Show in side menu
copyright = "&copy; 2016 Røa Storband<br> ved Helge Francke"
canonifyurls = true
paginate = 10

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "Stiftet 1974"
  brand = "Røa Storband"
  googleAnalytics = "UA-75781928-1"
  disqus = "Your Disqus shortname"
  dateFormat = "02 Jan 2006, 15:04"
  description = "Trenger du storband? Røa Storband gjør dansejobber, klubbjobber og konsertjobber i Oslo-området."

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Hjem"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Historie"
    pre = "<i class='fa fa-book fa-fw'></i>"
    weight = 1
    identifier = "historie"
    url = "/historie/"
  #[[menu.main]]
  #  name = "Konserter"
  #  pre = "<i class='fa fa-music fa-fw'></i>"
  #  weight = 2
  #  identifier = "concert"
  #  url = "/concert/"
  [[menu.main]]
    name = "Bandet"
    pre = "<i class='fa fa-users fa-fw'></i>"
    weight = 3
    identifier = "bandet"
    url = "/bandet/"
  [[menu.main]]
    name = "Booking"
    pre = "<i class='fa fa-phone fa-fw'></i>"
    weight = 4
    url = "/booking/"
  [[menu.main]]
    name = "Media"
    pre = "<i class='fa fa-play fa-fw'></i>"
    weight = 5
    url = "/media/"
  [[menu.main]]
    name = "Repertoar"
    pre = "<i class='fa fa-music fa-fw'></i>"
    weight = 6
    url = "/repertoar/"
  [[menu.main]]
    name = "Referanser"
    pre = "<i class='fa fa-heart fa-fw'></i>"
    weight = 7
    url = "/referanser/"

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.

  # SNS microblogging
  facebook = "Røa-Storband-154150207956031"

  # SNS photo/video sharing
  # youtube = "*"
